### ISSUE TITLE
Compatibility with new vscode version

### ISSUE THREAD

**Issue by fanmanpro** [SimonSiefke/prettier-vscode#16]
Getting this when I try install from vscode.

![image](https://user-images.githubusercontent.com/1243998/74053894-7d10bd00-49a2-11ea-9631-8727cbc1a707.png)

**Comment by SimonSiefke** [comment]
I have now changed the `vscode.engines` field from `1.41.1` to `1.30.0`. Let me know if that works. :)

**Comment by SimonSiefke** [comment]
@fanmanpro Are you still experiencing this issue?

**Comment by fanmanpro** [comment]
Yea sorry its all good now. Thanks a lot 👍
