### ISSUE TITLE
CSS failures

### ISSUE THREAD

**Issue by AfdhalAtiffTan** [SimonSiefke/prettier-vscode#20]
Hi all,
I am using Svelte and I notice that the extension is not behaving properly.

The problem:
`grid-template-areas: "myArea myArea";`

will be automatically formatted into:
`grid-template-areas: 'myArea myArea';`

The conversion of the double-quote into the single-quote is breaking my CSS.

I cannot find any config file to change the default behavior.
Any workaround for this?

Thank you.

**Comment by SimonSiefke** [comment]
As far as I know, single and double quotes can be used interchangeably in CSS, so `grid-template-areas: "myArea myArea";` *should* work the same as `grid-template-areas: "myArea myArea";`. 

If you want to change the default behavior of prettier, you can create a `.prettierrc` file with 
```json
{
  "semi": false,
  "singleQuote": false
}
```
The [Prettier docs](https://prettier.io/docs/en/configuration.html) have more information about configuration.

Hope this helps!

**Comment by AfdhalAtiffTan** [comment]
Whoops, I spoke too soon, just found a bug in my other component. The link really helps, thank you!

**Comment by SimonSiefke** [comment]
I'm glad I could help :)
